/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Layout, QuestionInput } from "@24hc/shared";
import { Flashcard } from "./services/flashcards";
export { Layout, QuestionInput } from "@24hc/shared";
export { Flashcard } from "./services/flashcards";
export namespace Components {
    /**
     * The site-wide announcement. An <aside>, not a live region: it is static
     * content, not a response to a user action, and live regions inside shadow
     * roots announce unevenly. Not dismissible (one admin, one notice).
     */
    interface AppBanner {
    }
    interface AppFooter {
    }
    interface AppHeader {
        /**
          * reflect: true is load-bearing -- app-header.css keys on :host([orientation]).
          * @default 'horizontal'
         */
        "orientation": 'horizontal' | 'vertical';
    }
    /**
     * One component for every layout, switched by a reflected prop. A wrapper
     * TAG change (<layout-stacked> -> <layout-rail>) would make Stencil's vdom
     * rebuild the subtree, remounting the slotted header/page/footer and
     * re-firing their fetches; a prop change re-renders only this shadow tree
     * and the light-DOM children stay put.
     */
    interface AppLayout {
        /**
          * reflect: true is load-bearing -- app-layout.css keys on :host([bare]). Set by app-root for the print page.
          * @default false
         */
        "bare": boolean;
        /**
          * reflect: true is load-bearing -- app-layout.css keys on :host([layout]).
          * @default 'stacked'
         */
        "layout": Layout;
    }
    interface AppRoot {
    }
    /**
     * Plays a parsed `.flashcards.md` deck: one card at a time, front first,
     * flip to the back, step or shuffle. All state is local -- nothing is
     * persisted, so reloading starts the deck over.
     */
    interface FlashcardDeck {
        /**
          * @default []
         */
        "cards": Flashcard[];
        /**
          * Which side is up. A reflected prop rather than
          * @State because flashcard-deck.css keys on :host([flipped]) for the back's styling.
          * @default false
         */
        "flipped": boolean;
    }
    interface PageAttempt {
        "attemptId"?: number;
    }
    interface PageConnections {
    }
    interface PageForgotPassword {
    }
    interface PageGeneration {
        "generationId"?: number;
    }
    interface PageHome {
    }
    interface PageIntegrations {
    }
    interface PageLibrary {
        /**
          * Which segment is showing. reflect: true is load-bearing -- page-library.css keys on :host([kind='materials']) for the wider grid the extra type and size cells need.
          * @default 'tests'
         */
        "kind": 'tests' | 'materials';
    }
    interface PageLogin {
    }
    interface PageMaterial {
        "materialId"?: number;
    }
    interface PageMaterialForm {
        /**
          * Undefined = creating (/materials/new); set = editing (/materials/:id/edit).
         */
        "materialId"?: number;
    }
    interface PageMaterialShare {
        "materialId"?: number;
    }
    interface PageMaterials {
    }
    interface PageNotifications {
    }
    interface PageProfile {
    }
    interface PageRegister {
    }
    interface PageRegisterRole {
    }
    interface PageResetPassword {
    }
    interface PageTeacherProfile {
        "teacherId"?: number;
    }
    interface PageTeachers {
    }
    interface PageTest {
        "testId"?: number;
    }
    interface PageTestAssign {
        "testId"?: number;
    }
    interface PageTestEditor {
        /**
          * Undefined = creating a new test.
         */
        "testId"?: number;
    }
    interface PageTestGenerate {
    }
    interface PageTestPrint {
        "testId"?: number;
    }
    interface PageTestResults {
        "testId"?: number;
    }
    interface PageTests {
    }
    interface PageVerifyEmail {
    }
    /**
     * Author text -- a prompt, a stimulus, a rationale, a study guide -- in the
     * markdown subset `services/rich-text` understands. Vnodes only; see that
     * file for why there is no sanitizer.
     */
    interface RichText {
        /**
          * Headings, lists, quotes, fences, rules and links: on for materials, off for questions.
          * @default false
         */
        "blocks": boolean;
        /**
          * @default ''
         */
        "text": string;
    }
    interface TestQuestionEditor {
        "error"?: string;
        /**
          * @default 0
         */
        "index": number;
        /**
          * The previous question's stimulus, offered as a one-click copy so a set shares it verbatim.
         */
        "previousStimulus"?: string | null;
        "question": QuestionInput;
    }
}
export interface TestQuestionEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTestQuestionEditorElement;
}
declare global {
    /**
     * The site-wide announcement. An <aside>, not a live region: it is static
     * content, not a response to a user action, and live regions inside shadow
     * roots announce unevenly. Not dismissible (one admin, one notice).
     */
    interface HTMLAppBannerElement extends Components.AppBanner, HTMLStencilElement {
    }
    var HTMLAppBannerElement: {
        prototype: HTMLAppBannerElement;
        new (): HTMLAppBannerElement;
    };
    interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {
    }
    var HTMLAppFooterElement: {
        prototype: HTMLAppFooterElement;
        new (): HTMLAppFooterElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    /**
     * One component for every layout, switched by a reflected prop. A wrapper
     * TAG change (<layout-stacked> -> <layout-rail>) would make Stencil's vdom
     * rebuild the subtree, remounting the slotted header/page/footer and
     * re-firing their fetches; a prop change re-renders only this shadow tree
     * and the light-DOM children stay put.
     */
    interface HTMLAppLayoutElement extends Components.AppLayout, HTMLStencilElement {
    }
    var HTMLAppLayoutElement: {
        prototype: HTMLAppLayoutElement;
        new (): HTMLAppLayoutElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    /**
     * Plays a parsed `.flashcards.md` deck: one card at a time, front first,
     * flip to the back, step or shuffle. All state is local -- nothing is
     * persisted, so reloading starts the deck over.
     */
    interface HTMLFlashcardDeckElement extends Components.FlashcardDeck, HTMLStencilElement {
    }
    var HTMLFlashcardDeckElement: {
        prototype: HTMLFlashcardDeckElement;
        new (): HTMLFlashcardDeckElement;
    };
    interface HTMLPageAttemptElement extends Components.PageAttempt, HTMLStencilElement {
    }
    var HTMLPageAttemptElement: {
        prototype: HTMLPageAttemptElement;
        new (): HTMLPageAttemptElement;
    };
    interface HTMLPageConnectionsElement extends Components.PageConnections, HTMLStencilElement {
    }
    var HTMLPageConnectionsElement: {
        prototype: HTMLPageConnectionsElement;
        new (): HTMLPageConnectionsElement;
    };
    interface HTMLPageForgotPasswordElement extends Components.PageForgotPassword, HTMLStencilElement {
    }
    var HTMLPageForgotPasswordElement: {
        prototype: HTMLPageForgotPasswordElement;
        new (): HTMLPageForgotPasswordElement;
    };
    interface HTMLPageGenerationElement extends Components.PageGeneration, HTMLStencilElement {
    }
    var HTMLPageGenerationElement: {
        prototype: HTMLPageGenerationElement;
        new (): HTMLPageGenerationElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageIntegrationsElement extends Components.PageIntegrations, HTMLStencilElement {
    }
    var HTMLPageIntegrationsElement: {
        prototype: HTMLPageIntegrationsElement;
        new (): HTMLPageIntegrationsElement;
    };
    interface HTMLPageLibraryElement extends Components.PageLibrary, HTMLStencilElement {
    }
    var HTMLPageLibraryElement: {
        prototype: HTMLPageLibraryElement;
        new (): HTMLPageLibraryElement;
    };
    interface HTMLPageLoginElement extends Components.PageLogin, HTMLStencilElement {
    }
    var HTMLPageLoginElement: {
        prototype: HTMLPageLoginElement;
        new (): HTMLPageLoginElement;
    };
    interface HTMLPageMaterialElement extends Components.PageMaterial, HTMLStencilElement {
    }
    var HTMLPageMaterialElement: {
        prototype: HTMLPageMaterialElement;
        new (): HTMLPageMaterialElement;
    };
    interface HTMLPageMaterialFormElement extends Components.PageMaterialForm, HTMLStencilElement {
    }
    var HTMLPageMaterialFormElement: {
        prototype: HTMLPageMaterialFormElement;
        new (): HTMLPageMaterialFormElement;
    };
    interface HTMLPageMaterialShareElement extends Components.PageMaterialShare, HTMLStencilElement {
    }
    var HTMLPageMaterialShareElement: {
        prototype: HTMLPageMaterialShareElement;
        new (): HTMLPageMaterialShareElement;
    };
    interface HTMLPageMaterialsElement extends Components.PageMaterials, HTMLStencilElement {
    }
    var HTMLPageMaterialsElement: {
        prototype: HTMLPageMaterialsElement;
        new (): HTMLPageMaterialsElement;
    };
    interface HTMLPageNotificationsElement extends Components.PageNotifications, HTMLStencilElement {
    }
    var HTMLPageNotificationsElement: {
        prototype: HTMLPageNotificationsElement;
        new (): HTMLPageNotificationsElement;
    };
    interface HTMLPageProfileElement extends Components.PageProfile, HTMLStencilElement {
    }
    var HTMLPageProfileElement: {
        prototype: HTMLPageProfileElement;
        new (): HTMLPageProfileElement;
    };
    interface HTMLPageRegisterElement extends Components.PageRegister, HTMLStencilElement {
    }
    var HTMLPageRegisterElement: {
        prototype: HTMLPageRegisterElement;
        new (): HTMLPageRegisterElement;
    };
    interface HTMLPageRegisterRoleElement extends Components.PageRegisterRole, HTMLStencilElement {
    }
    var HTMLPageRegisterRoleElement: {
        prototype: HTMLPageRegisterRoleElement;
        new (): HTMLPageRegisterRoleElement;
    };
    interface HTMLPageResetPasswordElement extends Components.PageResetPassword, HTMLStencilElement {
    }
    var HTMLPageResetPasswordElement: {
        prototype: HTMLPageResetPasswordElement;
        new (): HTMLPageResetPasswordElement;
    };
    interface HTMLPageTeacherProfileElement extends Components.PageTeacherProfile, HTMLStencilElement {
    }
    var HTMLPageTeacherProfileElement: {
        prototype: HTMLPageTeacherProfileElement;
        new (): HTMLPageTeacherProfileElement;
    };
    interface HTMLPageTeachersElement extends Components.PageTeachers, HTMLStencilElement {
    }
    var HTMLPageTeachersElement: {
        prototype: HTMLPageTeachersElement;
        new (): HTMLPageTeachersElement;
    };
    interface HTMLPageTestElement extends Components.PageTest, HTMLStencilElement {
    }
    var HTMLPageTestElement: {
        prototype: HTMLPageTestElement;
        new (): HTMLPageTestElement;
    };
    interface HTMLPageTestAssignElement extends Components.PageTestAssign, HTMLStencilElement {
    }
    var HTMLPageTestAssignElement: {
        prototype: HTMLPageTestAssignElement;
        new (): HTMLPageTestAssignElement;
    };
    interface HTMLPageTestEditorElement extends Components.PageTestEditor, HTMLStencilElement {
    }
    var HTMLPageTestEditorElement: {
        prototype: HTMLPageTestEditorElement;
        new (): HTMLPageTestEditorElement;
    };
    interface HTMLPageTestGenerateElement extends Components.PageTestGenerate, HTMLStencilElement {
    }
    var HTMLPageTestGenerateElement: {
        prototype: HTMLPageTestGenerateElement;
        new (): HTMLPageTestGenerateElement;
    };
    interface HTMLPageTestPrintElement extends Components.PageTestPrint, HTMLStencilElement {
    }
    var HTMLPageTestPrintElement: {
        prototype: HTMLPageTestPrintElement;
        new (): HTMLPageTestPrintElement;
    };
    interface HTMLPageTestResultsElement extends Components.PageTestResults, HTMLStencilElement {
    }
    var HTMLPageTestResultsElement: {
        prototype: HTMLPageTestResultsElement;
        new (): HTMLPageTestResultsElement;
    };
    interface HTMLPageTestsElement extends Components.PageTests, HTMLStencilElement {
    }
    var HTMLPageTestsElement: {
        prototype: HTMLPageTestsElement;
        new (): HTMLPageTestsElement;
    };
    interface HTMLPageVerifyEmailElement extends Components.PageVerifyEmail, HTMLStencilElement {
    }
    var HTMLPageVerifyEmailElement: {
        prototype: HTMLPageVerifyEmailElement;
        new (): HTMLPageVerifyEmailElement;
    };
    /**
     * Author text -- a prompt, a stimulus, a rationale, a study guide -- in the
     * markdown subset `services/rich-text` understands. Vnodes only; see that
     * file for why there is no sanitizer.
     */
    interface HTMLRichTextElement extends Components.RichText, HTMLStencilElement {
    }
    var HTMLRichTextElement: {
        prototype: HTMLRichTextElement;
        new (): HTMLRichTextElement;
    };
    interface HTMLTestQuestionEditorElementEventMap {
        "questionChange": QuestionInput;
        "questionRemove": void;
        "questionMove": -1 | 1;
    }
    interface HTMLTestQuestionEditorElement extends Components.TestQuestionEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTestQuestionEditorElementEventMap>(type: K, listener: (this: HTMLTestQuestionEditorElement, ev: TestQuestionEditorCustomEvent<HTMLTestQuestionEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTestQuestionEditorElementEventMap>(type: K, listener: (this: HTMLTestQuestionEditorElement, ev: TestQuestionEditorCustomEvent<HTMLTestQuestionEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTestQuestionEditorElement: {
        prototype: HTMLTestQuestionEditorElement;
        new (): HTMLTestQuestionEditorElement;
    };
    interface HTMLElementTagNameMap {
        "app-banner": HTMLAppBannerElement;
        "app-footer": HTMLAppFooterElement;
        "app-header": HTMLAppHeaderElement;
        "app-layout": HTMLAppLayoutElement;
        "app-root": HTMLAppRootElement;
        "flashcard-deck": HTMLFlashcardDeckElement;
        "page-attempt": HTMLPageAttemptElement;
        "page-connections": HTMLPageConnectionsElement;
        "page-forgot-password": HTMLPageForgotPasswordElement;
        "page-generation": HTMLPageGenerationElement;
        "page-home": HTMLPageHomeElement;
        "page-integrations": HTMLPageIntegrationsElement;
        "page-library": HTMLPageLibraryElement;
        "page-login": HTMLPageLoginElement;
        "page-material": HTMLPageMaterialElement;
        "page-material-form": HTMLPageMaterialFormElement;
        "page-material-share": HTMLPageMaterialShareElement;
        "page-materials": HTMLPageMaterialsElement;
        "page-notifications": HTMLPageNotificationsElement;
        "page-profile": HTMLPageProfileElement;
        "page-register": HTMLPageRegisterElement;
        "page-register-role": HTMLPageRegisterRoleElement;
        "page-reset-password": HTMLPageResetPasswordElement;
        "page-teacher-profile": HTMLPageTeacherProfileElement;
        "page-teachers": HTMLPageTeachersElement;
        "page-test": HTMLPageTestElement;
        "page-test-assign": HTMLPageTestAssignElement;
        "page-test-editor": HTMLPageTestEditorElement;
        "page-test-generate": HTMLPageTestGenerateElement;
        "page-test-print": HTMLPageTestPrintElement;
        "page-test-results": HTMLPageTestResultsElement;
        "page-tests": HTMLPageTestsElement;
        "page-verify-email": HTMLPageVerifyEmailElement;
        "rich-text": HTMLRichTextElement;
        "test-question-editor": HTMLTestQuestionEditorElement;
    }
}
declare namespace LocalJSX {
    /**
     * The site-wide announcement. An <aside>, not a live region: it is static
     * content, not a response to a user action, and live regions inside shadow
     * roots announce unevenly. Not dismissible (one admin, one notice).
     */
    interface AppBanner {
    }
    interface AppFooter {
    }
    interface AppHeader {
        /**
          * reflect: true is load-bearing -- app-header.css keys on :host([orientation]).
          * @default 'horizontal'
         */
        "orientation"?: 'horizontal' | 'vertical';
    }
    /**
     * One component for every layout, switched by a reflected prop. A wrapper
     * TAG change (<layout-stacked> -> <layout-rail>) would make Stencil's vdom
     * rebuild the subtree, remounting the slotted header/page/footer and
     * re-firing their fetches; a prop change re-renders only this shadow tree
     * and the light-DOM children stay put.
     */
    interface AppLayout {
        /**
          * reflect: true is load-bearing -- app-layout.css keys on :host([bare]). Set by app-root for the print page.
          * @default false
         */
        "bare"?: boolean;
        /**
          * reflect: true is load-bearing -- app-layout.css keys on :host([layout]).
          * @default 'stacked'
         */
        "layout"?: Layout;
    }
    interface AppRoot {
    }
    /**
     * Plays a parsed `.flashcards.md` deck: one card at a time, front first,
     * flip to the back, step or shuffle. All state is local -- nothing is
     * persisted, so reloading starts the deck over.
     */
    interface FlashcardDeck {
        /**
          * @default []
         */
        "cards"?: Flashcard[];
        /**
          * Which side is up. A reflected prop rather than
          * @State because flashcard-deck.css keys on :host([flipped]) for the back's styling.
          * @default false
         */
        "flipped"?: boolean;
    }
    interface PageAttempt {
        "attemptId"?: number;
    }
    interface PageConnections {
    }
    interface PageForgotPassword {
    }
    interface PageGeneration {
        "generationId"?: number;
    }
    interface PageHome {
    }
    interface PageIntegrations {
    }
    interface PageLibrary {
        /**
          * Which segment is showing. reflect: true is load-bearing -- page-library.css keys on :host([kind='materials']) for the wider grid the extra type and size cells need.
          * @default 'tests'
         */
        "kind"?: 'tests' | 'materials';
    }
    interface PageLogin {
    }
    interface PageMaterial {
        "materialId"?: number;
    }
    interface PageMaterialForm {
        /**
          * Undefined = creating (/materials/new); set = editing (/materials/:id/edit).
         */
        "materialId"?: number;
    }
    interface PageMaterialShare {
        "materialId"?: number;
    }
    interface PageMaterials {
    }
    interface PageNotifications {
    }
    interface PageProfile {
    }
    interface PageRegister {
    }
    interface PageRegisterRole {
    }
    interface PageResetPassword {
    }
    interface PageTeacherProfile {
        "teacherId"?: number;
    }
    interface PageTeachers {
    }
    interface PageTest {
        "testId"?: number;
    }
    interface PageTestAssign {
        "testId"?: number;
    }
    interface PageTestEditor {
        /**
          * Undefined = creating a new test.
         */
        "testId"?: number;
    }
    interface PageTestGenerate {
    }
    interface PageTestPrint {
        "testId"?: number;
    }
    interface PageTestResults {
        "testId"?: number;
    }
    interface PageTests {
    }
    interface PageVerifyEmail {
    }
    /**
     * Author text -- a prompt, a stimulus, a rationale, a study guide -- in the
     * markdown subset `services/rich-text` understands. Vnodes only; see that
     * file for why there is no sanitizer.
     */
    interface RichText {
        /**
          * Headings, lists, quotes, fences, rules and links: on for materials, off for questions.
          * @default false
         */
        "blocks"?: boolean;
        /**
          * @default ''
         */
        "text"?: string;
    }
    interface TestQuestionEditor {
        "error"?: string;
        /**
          * @default 0
         */
        "index"?: number;
        "onQuestionChange"?: (event: TestQuestionEditorCustomEvent<QuestionInput>) => void;
        "onQuestionMove"?: (event: TestQuestionEditorCustomEvent<-1 | 1>) => void;
        "onQuestionRemove"?: (event: TestQuestionEditorCustomEvent<void>) => void;
        /**
          * The previous question's stimulus, offered as a one-click copy so a set shares it verbatim.
         */
        "previousStimulus"?: string | null;
        "question"?: QuestionInput;
    }

    interface AppHeaderAttributes {
        "orientation": 'horizontal' | 'vertical';
    }
    interface AppLayoutAttributes {
        "layout": Layout;
        "bare": boolean;
    }
    interface FlashcardDeckAttributes {
        "flipped": boolean;
    }
    interface PageAttemptAttributes {
        "attemptId": number;
    }
    interface PageGenerationAttributes {
        "generationId": number;
    }
    interface PageLibraryAttributes {
        "kind": 'tests' | 'materials';
    }
    interface PageMaterialAttributes {
        "materialId": number;
    }
    interface PageMaterialFormAttributes {
        "materialId": number;
    }
    interface PageMaterialShareAttributes {
        "materialId": number;
    }
    interface PageTeacherProfileAttributes {
        "teacherId": number;
    }
    interface PageTestAttributes {
        "testId": number;
    }
    interface PageTestAssignAttributes {
        "testId": number;
    }
    interface PageTestEditorAttributes {
        "testId": number;
    }
    interface PageTestPrintAttributes {
        "testId": number;
    }
    interface PageTestResultsAttributes {
        "testId": number;
    }
    interface RichTextAttributes {
        "text": string;
        "blocks": boolean;
    }
    interface TestQuestionEditorAttributes {
        "index": number;
        "error": string;
        "previousStimulus": string | null;
    }

    interface IntrinsicElements {
        "app-banner": AppBanner;
        "app-footer": AppFooter;
        "app-header": Omit<AppHeader, keyof AppHeaderAttributes> & { [K in keyof AppHeader & keyof AppHeaderAttributes]?: AppHeader[K] } & { [K in keyof AppHeader & keyof AppHeaderAttributes as `attr:${K}`]?: AppHeaderAttributes[K] } & { [K in keyof AppHeader & keyof AppHeaderAttributes as `prop:${K}`]?: AppHeader[K] };
        "app-layout": Omit<AppLayout, keyof AppLayoutAttributes> & { [K in keyof AppLayout & keyof AppLayoutAttributes]?: AppLayout[K] } & { [K in keyof AppLayout & keyof AppLayoutAttributes as `attr:${K}`]?: AppLayoutAttributes[K] } & { [K in keyof AppLayout & keyof AppLayoutAttributes as `prop:${K}`]?: AppLayout[K] };
        "app-root": AppRoot;
        "flashcard-deck": Omit<FlashcardDeck, keyof FlashcardDeckAttributes> & { [K in keyof FlashcardDeck & keyof FlashcardDeckAttributes]?: FlashcardDeck[K] } & { [K in keyof FlashcardDeck & keyof FlashcardDeckAttributes as `attr:${K}`]?: FlashcardDeckAttributes[K] } & { [K in keyof FlashcardDeck & keyof FlashcardDeckAttributes as `prop:${K}`]?: FlashcardDeck[K] };
        "page-attempt": Omit<PageAttempt, keyof PageAttemptAttributes> & { [K in keyof PageAttempt & keyof PageAttemptAttributes]?: PageAttempt[K] } & { [K in keyof PageAttempt & keyof PageAttemptAttributes as `attr:${K}`]?: PageAttemptAttributes[K] } & { [K in keyof PageAttempt & keyof PageAttemptAttributes as `prop:${K}`]?: PageAttempt[K] };
        "page-connections": PageConnections;
        "page-forgot-password": PageForgotPassword;
        "page-generation": Omit<PageGeneration, keyof PageGenerationAttributes> & { [K in keyof PageGeneration & keyof PageGenerationAttributes]?: PageGeneration[K] } & { [K in keyof PageGeneration & keyof PageGenerationAttributes as `attr:${K}`]?: PageGenerationAttributes[K] } & { [K in keyof PageGeneration & keyof PageGenerationAttributes as `prop:${K}`]?: PageGeneration[K] };
        "page-home": PageHome;
        "page-integrations": PageIntegrations;
        "page-library": Omit<PageLibrary, keyof PageLibraryAttributes> & { [K in keyof PageLibrary & keyof PageLibraryAttributes]?: PageLibrary[K] } & { [K in keyof PageLibrary & keyof PageLibraryAttributes as `attr:${K}`]?: PageLibraryAttributes[K] } & { [K in keyof PageLibrary & keyof PageLibraryAttributes as `prop:${K}`]?: PageLibrary[K] };
        "page-login": PageLogin;
        "page-material": Omit<PageMaterial, keyof PageMaterialAttributes> & { [K in keyof PageMaterial & keyof PageMaterialAttributes]?: PageMaterial[K] } & { [K in keyof PageMaterial & keyof PageMaterialAttributes as `attr:${K}`]?: PageMaterialAttributes[K] } & { [K in keyof PageMaterial & keyof PageMaterialAttributes as `prop:${K}`]?: PageMaterial[K] };
        "page-material-form": Omit<PageMaterialForm, keyof PageMaterialFormAttributes> & { [K in keyof PageMaterialForm & keyof PageMaterialFormAttributes]?: PageMaterialForm[K] } & { [K in keyof PageMaterialForm & keyof PageMaterialFormAttributes as `attr:${K}`]?: PageMaterialFormAttributes[K] } & { [K in keyof PageMaterialForm & keyof PageMaterialFormAttributes as `prop:${K}`]?: PageMaterialForm[K] };
        "page-material-share": Omit<PageMaterialShare, keyof PageMaterialShareAttributes> & { [K in keyof PageMaterialShare & keyof PageMaterialShareAttributes]?: PageMaterialShare[K] } & { [K in keyof PageMaterialShare & keyof PageMaterialShareAttributes as `attr:${K}`]?: PageMaterialShareAttributes[K] } & { [K in keyof PageMaterialShare & keyof PageMaterialShareAttributes as `prop:${K}`]?: PageMaterialShare[K] };
        "page-materials": PageMaterials;
        "page-notifications": PageNotifications;
        "page-profile": PageProfile;
        "page-register": PageRegister;
        "page-register-role": PageRegisterRole;
        "page-reset-password": PageResetPassword;
        "page-teacher-profile": Omit<PageTeacherProfile, keyof PageTeacherProfileAttributes> & { [K in keyof PageTeacherProfile & keyof PageTeacherProfileAttributes]?: PageTeacherProfile[K] } & { [K in keyof PageTeacherProfile & keyof PageTeacherProfileAttributes as `attr:${K}`]?: PageTeacherProfileAttributes[K] } & { [K in keyof PageTeacherProfile & keyof PageTeacherProfileAttributes as `prop:${K}`]?: PageTeacherProfile[K] };
        "page-teachers": PageTeachers;
        "page-test": Omit<PageTest, keyof PageTestAttributes> & { [K in keyof PageTest & keyof PageTestAttributes]?: PageTest[K] } & { [K in keyof PageTest & keyof PageTestAttributes as `attr:${K}`]?: PageTestAttributes[K] } & { [K in keyof PageTest & keyof PageTestAttributes as `prop:${K}`]?: PageTest[K] };
        "page-test-assign": Omit<PageTestAssign, keyof PageTestAssignAttributes> & { [K in keyof PageTestAssign & keyof PageTestAssignAttributes]?: PageTestAssign[K] } & { [K in keyof PageTestAssign & keyof PageTestAssignAttributes as `attr:${K}`]?: PageTestAssignAttributes[K] } & { [K in keyof PageTestAssign & keyof PageTestAssignAttributes as `prop:${K}`]?: PageTestAssign[K] };
        "page-test-editor": Omit<PageTestEditor, keyof PageTestEditorAttributes> & { [K in keyof PageTestEditor & keyof PageTestEditorAttributes]?: PageTestEditor[K] } & { [K in keyof PageTestEditor & keyof PageTestEditorAttributes as `attr:${K}`]?: PageTestEditorAttributes[K] } & { [K in keyof PageTestEditor & keyof PageTestEditorAttributes as `prop:${K}`]?: PageTestEditor[K] };
        "page-test-generate": PageTestGenerate;
        "page-test-print": Omit<PageTestPrint, keyof PageTestPrintAttributes> & { [K in keyof PageTestPrint & keyof PageTestPrintAttributes]?: PageTestPrint[K] } & { [K in keyof PageTestPrint & keyof PageTestPrintAttributes as `attr:${K}`]?: PageTestPrintAttributes[K] } & { [K in keyof PageTestPrint & keyof PageTestPrintAttributes as `prop:${K}`]?: PageTestPrint[K] };
        "page-test-results": Omit<PageTestResults, keyof PageTestResultsAttributes> & { [K in keyof PageTestResults & keyof PageTestResultsAttributes]?: PageTestResults[K] } & { [K in keyof PageTestResults & keyof PageTestResultsAttributes as `attr:${K}`]?: PageTestResultsAttributes[K] } & { [K in keyof PageTestResults & keyof PageTestResultsAttributes as `prop:${K}`]?: PageTestResults[K] };
        "page-tests": PageTests;
        "page-verify-email": PageVerifyEmail;
        "rich-text": Omit<RichText, keyof RichTextAttributes> & { [K in keyof RichText & keyof RichTextAttributes]?: RichText[K] } & { [K in keyof RichText & keyof RichTextAttributes as `attr:${K}`]?: RichTextAttributes[K] } & { [K in keyof RichText & keyof RichTextAttributes as `prop:${K}`]?: RichText[K] };
        "test-question-editor": Omit<TestQuestionEditor, keyof TestQuestionEditorAttributes> & { [K in keyof TestQuestionEditor & keyof TestQuestionEditorAttributes]?: TestQuestionEditor[K] } & { [K in keyof TestQuestionEditor & keyof TestQuestionEditorAttributes as `attr:${K}`]?: TestQuestionEditorAttributes[K] } & { [K in keyof TestQuestionEditor & keyof TestQuestionEditorAttributes as `prop:${K}`]?: TestQuestionEditor[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * The site-wide announcement. An <aside>, not a live region: it is static
             * content, not a response to a user action, and live regions inside shadow
             * roots announce unevenly. Not dismissible (one admin, one notice).
             */
            "app-banner": LocalJSX.IntrinsicElements["app-banner"] & JSXBase.HTMLAttributes<HTMLAppBannerElement>;
            "app-footer": LocalJSX.IntrinsicElements["app-footer"] & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
            "app-header": LocalJSX.IntrinsicElements["app-header"] & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            /**
             * One component for every layout, switched by a reflected prop. A wrapper
             * TAG change (<layout-stacked> -> <layout-rail>) would make Stencil's vdom
             * rebuild the subtree, remounting the slotted header/page/footer and
             * re-firing their fetches; a prop change re-renders only this shadow tree
             * and the light-DOM children stay put.
             */
            "app-layout": LocalJSX.IntrinsicElements["app-layout"] & JSXBase.HTMLAttributes<HTMLAppLayoutElement>;
            "app-root": LocalJSX.IntrinsicElements["app-root"] & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            /**
             * Plays a parsed `.flashcards.md` deck: one card at a time, front first,
             * flip to the back, step or shuffle. All state is local -- nothing is
             * persisted, so reloading starts the deck over.
             */
            "flashcard-deck": LocalJSX.IntrinsicElements["flashcard-deck"] & JSXBase.HTMLAttributes<HTMLFlashcardDeckElement>;
            "page-attempt": LocalJSX.IntrinsicElements["page-attempt"] & JSXBase.HTMLAttributes<HTMLPageAttemptElement>;
            "page-connections": LocalJSX.IntrinsicElements["page-connections"] & JSXBase.HTMLAttributes<HTMLPageConnectionsElement>;
            "page-forgot-password": LocalJSX.IntrinsicElements["page-forgot-password"] & JSXBase.HTMLAttributes<HTMLPageForgotPasswordElement>;
            "page-generation": LocalJSX.IntrinsicElements["page-generation"] & JSXBase.HTMLAttributes<HTMLPageGenerationElement>;
            "page-home": LocalJSX.IntrinsicElements["page-home"] & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-integrations": LocalJSX.IntrinsicElements["page-integrations"] & JSXBase.HTMLAttributes<HTMLPageIntegrationsElement>;
            "page-library": LocalJSX.IntrinsicElements["page-library"] & JSXBase.HTMLAttributes<HTMLPageLibraryElement>;
            "page-login": LocalJSX.IntrinsicElements["page-login"] & JSXBase.HTMLAttributes<HTMLPageLoginElement>;
            "page-material": LocalJSX.IntrinsicElements["page-material"] & JSXBase.HTMLAttributes<HTMLPageMaterialElement>;
            "page-material-form": LocalJSX.IntrinsicElements["page-material-form"] & JSXBase.HTMLAttributes<HTMLPageMaterialFormElement>;
            "page-material-share": LocalJSX.IntrinsicElements["page-material-share"] & JSXBase.HTMLAttributes<HTMLPageMaterialShareElement>;
            "page-materials": LocalJSX.IntrinsicElements["page-materials"] & JSXBase.HTMLAttributes<HTMLPageMaterialsElement>;
            "page-notifications": LocalJSX.IntrinsicElements["page-notifications"] & JSXBase.HTMLAttributes<HTMLPageNotificationsElement>;
            "page-profile": LocalJSX.IntrinsicElements["page-profile"] & JSXBase.HTMLAttributes<HTMLPageProfileElement>;
            "page-register": LocalJSX.IntrinsicElements["page-register"] & JSXBase.HTMLAttributes<HTMLPageRegisterElement>;
            "page-register-role": LocalJSX.IntrinsicElements["page-register-role"] & JSXBase.HTMLAttributes<HTMLPageRegisterRoleElement>;
            "page-reset-password": LocalJSX.IntrinsicElements["page-reset-password"] & JSXBase.HTMLAttributes<HTMLPageResetPasswordElement>;
            "page-teacher-profile": LocalJSX.IntrinsicElements["page-teacher-profile"] & JSXBase.HTMLAttributes<HTMLPageTeacherProfileElement>;
            "page-teachers": LocalJSX.IntrinsicElements["page-teachers"] & JSXBase.HTMLAttributes<HTMLPageTeachersElement>;
            "page-test": LocalJSX.IntrinsicElements["page-test"] & JSXBase.HTMLAttributes<HTMLPageTestElement>;
            "page-test-assign": LocalJSX.IntrinsicElements["page-test-assign"] & JSXBase.HTMLAttributes<HTMLPageTestAssignElement>;
            "page-test-editor": LocalJSX.IntrinsicElements["page-test-editor"] & JSXBase.HTMLAttributes<HTMLPageTestEditorElement>;
            "page-test-generate": LocalJSX.IntrinsicElements["page-test-generate"] & JSXBase.HTMLAttributes<HTMLPageTestGenerateElement>;
            "page-test-print": LocalJSX.IntrinsicElements["page-test-print"] & JSXBase.HTMLAttributes<HTMLPageTestPrintElement>;
            "page-test-results": LocalJSX.IntrinsicElements["page-test-results"] & JSXBase.HTMLAttributes<HTMLPageTestResultsElement>;
            "page-tests": LocalJSX.IntrinsicElements["page-tests"] & JSXBase.HTMLAttributes<HTMLPageTestsElement>;
            "page-verify-email": LocalJSX.IntrinsicElements["page-verify-email"] & JSXBase.HTMLAttributes<HTMLPageVerifyEmailElement>;
            /**
             * Author text -- a prompt, a stimulus, a rationale, a study guide -- in the
             * markdown subset `services/rich-text` understands. Vnodes only; see that
             * file for why there is no sanitizer.
             */
            "rich-text": LocalJSX.IntrinsicElements["rich-text"] & JSXBase.HTMLAttributes<HTMLRichTextElement>;
            "test-question-editor": LocalJSX.IntrinsicElements["test-question-editor"] & JSXBase.HTMLAttributes<HTMLTestQuestionEditorElement>;
        }
    }
}
