/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Layout, QuestionInput } from "@24hc/shared";
export { Layout, QuestionInput } from "@24hc/shared";
export namespace Components {
    interface AppFooter {
    }
    interface AppHeader {
        /**
          * reflect: true is load-bearing -- app-header.css keys on :host([orientation]).
          * @default 'horizontal'
         */
        "orientation": 'horizontal' | 'vertical';
    }
    /**
     * One component for every layout, switched by a reflected prop. A wrapper
     * TAG change (<layout-stacked> -> <layout-rail>) would make Stencil's vdom
     * rebuild the subtree, remounting the slotted header/page/footer and
     * re-firing their fetches; a prop change re-renders only this shadow tree
     * and the light-DOM children stay put.
     */
    interface AppLayout {
        /**
          * reflect: true is load-bearing -- app-layout.css keys on :host([bare]). Set by app-root for the print page.
          * @default false
         */
        "bare": boolean;
        /**
          * reflect: true is load-bearing -- app-layout.css keys on :host([layout]).
          * @default 'stacked'
         */
        "layout": Layout;
    }
    interface AppRoot {
    }
    interface PageConnections {
    }
    interface PageForgotPassword {
    }
    interface PageHome {
    }
    interface PageLibrary {
    }
    interface PageLogin {
    }
    interface PageNotifications {
    }
    interface PageProfile {
    }
    interface PageRegister {
    }
    interface PageRegisterRole {
    }
    interface PageResetPassword {
    }
    interface PageTeacherProfile {
        "teacherId"?: number;
    }
    interface PageTeachers {
    }
    interface PageTest {
        "testId"?: number;
    }
    interface PageTestAssign {
        "testId"?: number;
    }
    interface PageTestEditor {
        /**
          * Undefined = creating a new test.
         */
        "testId"?: number;
    }
    interface PageTestResults {
        "testId"?: number;
    }
    interface PageTests {
    }
    interface PageVerifyEmail {
    }
    interface TestQuestionEditor {
        "error"?: string;
        /**
          * @default 0
         */
        "index": number;
        "question": QuestionInput;
    }
}
export interface TestQuestionEditorCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLTestQuestionEditorElement;
}
declare global {
    interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {
    }
    var HTMLAppFooterElement: {
        prototype: HTMLAppFooterElement;
        new (): HTMLAppFooterElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    /**
     * One component for every layout, switched by a reflected prop. A wrapper
     * TAG change (<layout-stacked> -> <layout-rail>) would make Stencil's vdom
     * rebuild the subtree, remounting the slotted header/page/footer and
     * re-firing their fetches; a prop change re-renders only this shadow tree
     * and the light-DOM children stay put.
     */
    interface HTMLAppLayoutElement extends Components.AppLayout, HTMLStencilElement {
    }
    var HTMLAppLayoutElement: {
        prototype: HTMLAppLayoutElement;
        new (): HTMLAppLayoutElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPageConnectionsElement extends Components.PageConnections, HTMLStencilElement {
    }
    var HTMLPageConnectionsElement: {
        prototype: HTMLPageConnectionsElement;
        new (): HTMLPageConnectionsElement;
    };
    interface HTMLPageForgotPasswordElement extends Components.PageForgotPassword, HTMLStencilElement {
    }
    var HTMLPageForgotPasswordElement: {
        prototype: HTMLPageForgotPasswordElement;
        new (): HTMLPageForgotPasswordElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageLibraryElement extends Components.PageLibrary, HTMLStencilElement {
    }
    var HTMLPageLibraryElement: {
        prototype: HTMLPageLibraryElement;
        new (): HTMLPageLibraryElement;
    };
    interface HTMLPageLoginElement extends Components.PageLogin, HTMLStencilElement {
    }
    var HTMLPageLoginElement: {
        prototype: HTMLPageLoginElement;
        new (): HTMLPageLoginElement;
    };
    interface HTMLPageNotificationsElement extends Components.PageNotifications, HTMLStencilElement {
    }
    var HTMLPageNotificationsElement: {
        prototype: HTMLPageNotificationsElement;
        new (): HTMLPageNotificationsElement;
    };
    interface HTMLPageProfileElement extends Components.PageProfile, HTMLStencilElement {
    }
    var HTMLPageProfileElement: {
        prototype: HTMLPageProfileElement;
        new (): HTMLPageProfileElement;
    };
    interface HTMLPageRegisterElement extends Components.PageRegister, HTMLStencilElement {
    }
    var HTMLPageRegisterElement: {
        prototype: HTMLPageRegisterElement;
        new (): HTMLPageRegisterElement;
    };
    interface HTMLPageRegisterRoleElement extends Components.PageRegisterRole, HTMLStencilElement {
    }
    var HTMLPageRegisterRoleElement: {
        prototype: HTMLPageRegisterRoleElement;
        new (): HTMLPageRegisterRoleElement;
    };
    interface HTMLPageResetPasswordElement extends Components.PageResetPassword, HTMLStencilElement {
    }
    var HTMLPageResetPasswordElement: {
        prototype: HTMLPageResetPasswordElement;
        new (): HTMLPageResetPasswordElement;
    };
    interface HTMLPageTeacherProfileElement extends Components.PageTeacherProfile, HTMLStencilElement {
    }
    var HTMLPageTeacherProfileElement: {
        prototype: HTMLPageTeacherProfileElement;
        new (): HTMLPageTeacherProfileElement;
    };
    interface HTMLPageTeachersElement extends Components.PageTeachers, HTMLStencilElement {
    }
    var HTMLPageTeachersElement: {
        prototype: HTMLPageTeachersElement;
        new (): HTMLPageTeachersElement;
    };
    interface HTMLPageTestElement extends Components.PageTest, HTMLStencilElement {
    }
    var HTMLPageTestElement: {
        prototype: HTMLPageTestElement;
        new (): HTMLPageTestElement;
    };
    interface HTMLPageTestAssignElement extends Components.PageTestAssign, HTMLStencilElement {
    }
    var HTMLPageTestAssignElement: {
        prototype: HTMLPageTestAssignElement;
        new (): HTMLPageTestAssignElement;
    };
    interface HTMLPageTestEditorElement extends Components.PageTestEditor, HTMLStencilElement {
    }
    var HTMLPageTestEditorElement: {
        prototype: HTMLPageTestEditorElement;
        new (): HTMLPageTestEditorElement;
    };
    interface HTMLPageTestResultsElement extends Components.PageTestResults, HTMLStencilElement {
    }
    var HTMLPageTestResultsElement: {
        prototype: HTMLPageTestResultsElement;
        new (): HTMLPageTestResultsElement;
    };
    interface HTMLPageTestsElement extends Components.PageTests, HTMLStencilElement {
    }
    var HTMLPageTestsElement: {
        prototype: HTMLPageTestsElement;
        new (): HTMLPageTestsElement;
    };
    interface HTMLPageVerifyEmailElement extends Components.PageVerifyEmail, HTMLStencilElement {
    }
    var HTMLPageVerifyEmailElement: {
        prototype: HTMLPageVerifyEmailElement;
        new (): HTMLPageVerifyEmailElement;
    };
    interface HTMLTestQuestionEditorElementEventMap {
        "questionChange": QuestionInput;
        "questionRemove": void;
        "questionMove": -1 | 1;
    }
    interface HTMLTestQuestionEditorElement extends Components.TestQuestionEditor, HTMLStencilElement {
        addEventListener<K extends keyof HTMLTestQuestionEditorElementEventMap>(type: K, listener: (this: HTMLTestQuestionEditorElement, ev: TestQuestionEditorCustomEvent<HTMLTestQuestionEditorElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLTestQuestionEditorElementEventMap>(type: K, listener: (this: HTMLTestQuestionEditorElement, ev: TestQuestionEditorCustomEvent<HTMLTestQuestionEditorElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLTestQuestionEditorElement: {
        prototype: HTMLTestQuestionEditorElement;
        new (): HTMLTestQuestionEditorElement;
    };
    interface HTMLElementTagNameMap {
        "app-footer": HTMLAppFooterElement;
        "app-header": HTMLAppHeaderElement;
        "app-layout": HTMLAppLayoutElement;
        "app-root": HTMLAppRootElement;
        "page-connections": HTMLPageConnectionsElement;
        "page-forgot-password": HTMLPageForgotPasswordElement;
        "page-home": HTMLPageHomeElement;
        "page-library": HTMLPageLibraryElement;
        "page-login": HTMLPageLoginElement;
        "page-notifications": HTMLPageNotificationsElement;
        "page-profile": HTMLPageProfileElement;
        "page-register": HTMLPageRegisterElement;
        "page-register-role": HTMLPageRegisterRoleElement;
        "page-reset-password": HTMLPageResetPasswordElement;
        "page-teacher-profile": HTMLPageTeacherProfileElement;
        "page-teachers": HTMLPageTeachersElement;
        "page-test": HTMLPageTestElement;
        "page-test-assign": HTMLPageTestAssignElement;
        "page-test-editor": HTMLPageTestEditorElement;
        "page-test-results": HTMLPageTestResultsElement;
        "page-tests": HTMLPageTestsElement;
        "page-verify-email": HTMLPageVerifyEmailElement;
        "test-question-editor": HTMLTestQuestionEditorElement;
    }
}
declare namespace LocalJSX {
    interface AppFooter {
    }
    interface AppHeader {
        /**
          * reflect: true is load-bearing -- app-header.css keys on :host([orientation]).
          * @default 'horizontal'
         */
        "orientation"?: 'horizontal' | 'vertical';
    }
    /**
     * One component for every layout, switched by a reflected prop. A wrapper
     * TAG change (<layout-stacked> -> <layout-rail>) would make Stencil's vdom
     * rebuild the subtree, remounting the slotted header/page/footer and
     * re-firing their fetches; a prop change re-renders only this shadow tree
     * and the light-DOM children stay put.
     */
    interface AppLayout {
        /**
          * reflect: true is load-bearing -- app-layout.css keys on :host([bare]). Set by app-root for the print page.
          * @default false
         */
        "bare"?: boolean;
        /**
          * reflect: true is load-bearing -- app-layout.css keys on :host([layout]).
          * @default 'stacked'
         */
        "layout"?: Layout;
    }
    interface AppRoot {
    }
    interface PageConnections {
    }
    interface PageForgotPassword {
    }
    interface PageHome {
    }
    interface PageLibrary {
    }
    interface PageLogin {
    }
    interface PageNotifications {
    }
    interface PageProfile {
    }
    interface PageRegister {
    }
    interface PageRegisterRole {
    }
    interface PageResetPassword {
    }
    interface PageTeacherProfile {
        "teacherId"?: number;
    }
    interface PageTeachers {
    }
    interface PageTest {
        "testId"?: number;
    }
    interface PageTestAssign {
        "testId"?: number;
    }
    interface PageTestEditor {
        /**
          * Undefined = creating a new test.
         */
        "testId"?: number;
    }
    interface PageTestResults {
        "testId"?: number;
    }
    interface PageTests {
    }
    interface PageVerifyEmail {
    }
    interface TestQuestionEditor {
        "error"?: string;
        /**
          * @default 0
         */
        "index"?: number;
        "onQuestionChange"?: (event: TestQuestionEditorCustomEvent<QuestionInput>) => void;
        "onQuestionMove"?: (event: TestQuestionEditorCustomEvent<-1 | 1>) => void;
        "onQuestionRemove"?: (event: TestQuestionEditorCustomEvent<void>) => void;
        "question"?: QuestionInput;
    }

    interface AppHeaderAttributes {
        "orientation": 'horizontal' | 'vertical';
    }
    interface AppLayoutAttributes {
        "layout": Layout;
        "bare": boolean;
    }
    interface PageTeacherProfileAttributes {
        "teacherId": number;
    }
    interface PageTestAttributes {
        "testId": number;
    }
    interface PageTestAssignAttributes {
        "testId": number;
    }
    interface PageTestEditorAttributes {
        "testId": number;
    }
    interface PageTestResultsAttributes {
        "testId": number;
    }
    interface TestQuestionEditorAttributes {
        "index": number;
        "error": string;
    }

    interface IntrinsicElements {
        "app-footer": AppFooter;
        "app-header": Omit<AppHeader, keyof AppHeaderAttributes> & { [K in keyof AppHeader & keyof AppHeaderAttributes]?: AppHeader[K] } & { [K in keyof AppHeader & keyof AppHeaderAttributes as `attr:${K}`]?: AppHeaderAttributes[K] } & { [K in keyof AppHeader & keyof AppHeaderAttributes as `prop:${K}`]?: AppHeader[K] };
        "app-layout": Omit<AppLayout, keyof AppLayoutAttributes> & { [K in keyof AppLayout & keyof AppLayoutAttributes]?: AppLayout[K] } & { [K in keyof AppLayout & keyof AppLayoutAttributes as `attr:${K}`]?: AppLayoutAttributes[K] } & { [K in keyof AppLayout & keyof AppLayoutAttributes as `prop:${K}`]?: AppLayout[K] };
        "app-root": AppRoot;
        "page-connections": PageConnections;
        "page-forgot-password": PageForgotPassword;
        "page-home": PageHome;
        "page-library": PageLibrary;
        "page-login": PageLogin;
        "page-notifications": PageNotifications;
        "page-profile": PageProfile;
        "page-register": PageRegister;
        "page-register-role": PageRegisterRole;
        "page-reset-password": PageResetPassword;
        "page-teacher-profile": Omit<PageTeacherProfile, keyof PageTeacherProfileAttributes> & { [K in keyof PageTeacherProfile & keyof PageTeacherProfileAttributes]?: PageTeacherProfile[K] } & { [K in keyof PageTeacherProfile & keyof PageTeacherProfileAttributes as `attr:${K}`]?: PageTeacherProfileAttributes[K] } & { [K in keyof PageTeacherProfile & keyof PageTeacherProfileAttributes as `prop:${K}`]?: PageTeacherProfile[K] };
        "page-teachers": PageTeachers;
        "page-test": Omit<PageTest, keyof PageTestAttributes> & { [K in keyof PageTest & keyof PageTestAttributes]?: PageTest[K] } & { [K in keyof PageTest & keyof PageTestAttributes as `attr:${K}`]?: PageTestAttributes[K] } & { [K in keyof PageTest & keyof PageTestAttributes as `prop:${K}`]?: PageTest[K] };
        "page-test-assign": Omit<PageTestAssign, keyof PageTestAssignAttributes> & { [K in keyof PageTestAssign & keyof PageTestAssignAttributes]?: PageTestAssign[K] } & { [K in keyof PageTestAssign & keyof PageTestAssignAttributes as `attr:${K}`]?: PageTestAssignAttributes[K] } & { [K in keyof PageTestAssign & keyof PageTestAssignAttributes as `prop:${K}`]?: PageTestAssign[K] };
        "page-test-editor": Omit<PageTestEditor, keyof PageTestEditorAttributes> & { [K in keyof PageTestEditor & keyof PageTestEditorAttributes]?: PageTestEditor[K] } & { [K in keyof PageTestEditor & keyof PageTestEditorAttributes as `attr:${K}`]?: PageTestEditorAttributes[K] } & { [K in keyof PageTestEditor & keyof PageTestEditorAttributes as `prop:${K}`]?: PageTestEditor[K] };
        "page-test-results": Omit<PageTestResults, keyof PageTestResultsAttributes> & { [K in keyof PageTestResults & keyof PageTestResultsAttributes]?: PageTestResults[K] } & { [K in keyof PageTestResults & keyof PageTestResultsAttributes as `attr:${K}`]?: PageTestResultsAttributes[K] } & { [K in keyof PageTestResults & keyof PageTestResultsAttributes as `prop:${K}`]?: PageTestResults[K] };
        "page-tests": PageTests;
        "page-verify-email": PageVerifyEmail;
        "test-question-editor": Omit<TestQuestionEditor, keyof TestQuestionEditorAttributes> & { [K in keyof TestQuestionEditor & keyof TestQuestionEditorAttributes]?: TestQuestionEditor[K] } & { [K in keyof TestQuestionEditor & keyof TestQuestionEditorAttributes as `attr:${K}`]?: TestQuestionEditorAttributes[K] } & { [K in keyof TestQuestionEditor & keyof TestQuestionEditorAttributes as `prop:${K}`]?: TestQuestionEditor[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-footer": LocalJSX.IntrinsicElements["app-footer"] & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
            "app-header": LocalJSX.IntrinsicElements["app-header"] & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            /**
             * One component for every layout, switched by a reflected prop. A wrapper
             * TAG change (<layout-stacked> -> <layout-rail>) would make Stencil's vdom
             * rebuild the subtree, remounting the slotted header/page/footer and
             * re-firing their fetches; a prop change re-renders only this shadow tree
             * and the light-DOM children stay put.
             */
            "app-layout": LocalJSX.IntrinsicElements["app-layout"] & JSXBase.HTMLAttributes<HTMLAppLayoutElement>;
            "app-root": LocalJSX.IntrinsicElements["app-root"] & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "page-connections": LocalJSX.IntrinsicElements["page-connections"] & JSXBase.HTMLAttributes<HTMLPageConnectionsElement>;
            "page-forgot-password": LocalJSX.IntrinsicElements["page-forgot-password"] & JSXBase.HTMLAttributes<HTMLPageForgotPasswordElement>;
            "page-home": LocalJSX.IntrinsicElements["page-home"] & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-library": LocalJSX.IntrinsicElements["page-library"] & JSXBase.HTMLAttributes<HTMLPageLibraryElement>;
            "page-login": LocalJSX.IntrinsicElements["page-login"] & JSXBase.HTMLAttributes<HTMLPageLoginElement>;
            "page-notifications": LocalJSX.IntrinsicElements["page-notifications"] & JSXBase.HTMLAttributes<HTMLPageNotificationsElement>;
            "page-profile": LocalJSX.IntrinsicElements["page-profile"] & JSXBase.HTMLAttributes<HTMLPageProfileElement>;
            "page-register": LocalJSX.IntrinsicElements["page-register"] & JSXBase.HTMLAttributes<HTMLPageRegisterElement>;
            "page-register-role": LocalJSX.IntrinsicElements["page-register-role"] & JSXBase.HTMLAttributes<HTMLPageRegisterRoleElement>;
            "page-reset-password": LocalJSX.IntrinsicElements["page-reset-password"] & JSXBase.HTMLAttributes<HTMLPageResetPasswordElement>;
            "page-teacher-profile": LocalJSX.IntrinsicElements["page-teacher-profile"] & JSXBase.HTMLAttributes<HTMLPageTeacherProfileElement>;
            "page-teachers": LocalJSX.IntrinsicElements["page-teachers"] & JSXBase.HTMLAttributes<HTMLPageTeachersElement>;
            "page-test": LocalJSX.IntrinsicElements["page-test"] & JSXBase.HTMLAttributes<HTMLPageTestElement>;
            "page-test-assign": LocalJSX.IntrinsicElements["page-test-assign"] & JSXBase.HTMLAttributes<HTMLPageTestAssignElement>;
            "page-test-editor": LocalJSX.IntrinsicElements["page-test-editor"] & JSXBase.HTMLAttributes<HTMLPageTestEditorElement>;
            "page-test-results": LocalJSX.IntrinsicElements["page-test-results"] & JSXBase.HTMLAttributes<HTMLPageTestResultsElement>;
            "page-tests": LocalJSX.IntrinsicElements["page-tests"] & JSXBase.HTMLAttributes<HTMLPageTestsElement>;
            "page-verify-email": LocalJSX.IntrinsicElements["page-verify-email"] & JSXBase.HTMLAttributes<HTMLPageVerifyEmailElement>;
            "test-question-editor": LocalJSX.IntrinsicElements["test-question-editor"] & JSXBase.HTMLAttributes<HTMLTestQuestionEditorElement>;
        }
    }
}
